accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views


app_name = "accounts"
urlpatterns = [
    path("login/", views.SubmittableLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("password-change/", views.SubmittablePasswordChange.as_view(), name="password_change"),
    path("sign-up/", views.SignUpView.as_view(), name="sign_up"),
]

my_site/urls.py
from django.contrib import admin
from django.urls import path, include
from viewer.views import MoviesView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', MoviesView.as_view(), name="index"),
    path("movie/", include('viewer.urls')),
    path("accounts/", include('accounts.urls')),
]

viewer/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create/', views.MovieCreateView.as_view(), name="movie_create"),
    path('update/<pk>/', views.MovieUpdateView.as_view(), name="movie_update"),
    path('delete/<pk>/', views.MovieDeleteView.as_view(), name="movie_delete"),
    path("details/<pk>/", views.MovieDetailView.as_view(), name="movie_details"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    biography = models.TextField(blank=True)

    def __str__(self):
        return f"{self.user.username}: {self.user.first_name} {self.user.last_name}"

viewer/models.py
from django.db.models import Model, CharField, ForeignKey, DO_NOTHING, IntegerField, DateField, TextField, DateTimeField

# Create your models here.
class Genre(Model):
    name = CharField(max_length=128)

    def __str__(self):
        return self.name


class Movie(Model):
    title = CharField(max_length=128)
    genre = ForeignKey(Genre, on_delete=DO_NOTHING)
    rating = IntegerField()
    released = DateField()
    description = TextField()
    created = DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import CharField, Textarea
from django.db.transaction import atomic
from .models import Profile


class SignUpForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        fields = ["username", "first_name"]

    biography = CharField(
        label="Biography",
        widget=Textarea(attrs={'placeholder': 'Tell us your story with movies'}),
        min_length=20
    )

    @atomic
    def save(self, commit=True):
        result = super().save(commit)
        # self.instance.is_active = False
        written_bio = self.cleaned_data["biography"]
        profile = Profile(biography=written_bio, user=result)
        if commit:
            profile.save()
        return result

viewer/forms.py
from django.forms import ModelForm, CharField, ModelChoiceField, IntegerField, DateField, Textarea
from django.core.exceptions import ValidationError
from .models import Genre, Movie
from datetime import date
import re

class PastDateField(DateField):

    def validate(self, value):
        super().validate(value)
        if value >= date.today():
            raise ValidationError("Only past dates allowed here")

    def clean(self, value):
        result = super().clean(value)
        return date(year=result.year, month=result.month, day=1)


def capitalized_validator(value):
    if value[0].islower():
        raise ValidationError("Value must be capitalized")


class MovieForm(ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'

    title = CharField(validators=[capitalized_validator])
    rating = IntegerField(min_value=1, max_value=10)
    released = PastDateField()

    def clean_description(self):
        initial = self.cleaned_data["description"]
        sentences = re.sub(r"\s*\.\s*", ".", initial).split(".")
        return ". ".join(sentence.capitalize() for sentence in sentences)

    def clean(self):
        result = super().clean()
        if result["genre"].name == "Comedy" and result["rating"] > 6:
            self.add_error("genre", ValidationError("Genre is comedy"))
            self.add_error("rating", ValidationError(f"Rating is {result['rating']}"))
            raise ValidationError("No comedy shall have a rating above 6")
        return result

accounts/views.py
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.views.generic import CreateView
from django.urls import reverse_lazy
from django.contrib import messages
from .forms import SignUpForm


class SubmittableLoginView(LoginView):
    template_name = "form.html"


class SubmittablePasswordChange(PasswordChangeView):
    template_name = "form.html"
    success_url = reverse_lazy("index")

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, "Password Changed successfully")
        return result


class SignUpView(CreateView):
    template_name = "form.html"
    form_class = SignUpForm
    success_url = reverse_lazy("accounts:login")

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, "User Created successfully")
        return result

viewer/views.py
from django.urls import reverse_lazy
from django.contrib.auth.models import Group
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.contrib import messages
from .models import Movie
from .forms import MovieForm
from logging import getLogger

LOGGER = getLogger()


class EditorRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        editors_group = Group.objects.get(name="Editors")
        user_groups = self.request.user.groups.all()
        if editors_group in user_groups:
            return True
        else:
            return False
        # return editors_group in user_groups


class MoviesView(ListView):
    template_name = "viewer/movies.html"
    model = Movie


class MovieCreateView(PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    template_name = "form.html"
    form_class = MovieForm
    success_url = reverse_lazy("movie_create")
    permission_required = "viewer.add_movie"

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, "Movie added successfully")
        return result


    def form_invalid(self, form):
        messages.warning(self.request, "Invalid form")
        LOGGER.warning("User provided invalid data")
        return super().form_invalid(form)


class MovieUpdateView(EditorRequiredMixin, PermissionRequiredMixin, UpdateView):
    template_name = "form.html"
    model = Movie
    form_class = MovieForm
    success_url = reverse_lazy("index")
    permission_required = "viewer.change_movie"

    def form_invalid(self, form):
        messages.warning(self.request, "Invalid form")
        LOGGER.warning("User provided invalid data during update of the movie")
        return super().form_invalid(form)


class MovieDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = "viewer/movie_confirm_delete.html"
    model = Movie
    success_url = reverse_lazy("index")
    permission_required = "viewer.delete_movie"


class MovieDetailView(DetailView):
    template_name = "viewer/movie_details.html"
    model = Movie

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_groups'] = self.request.user.groups.all()
        context['user_permissions'] = self.request.user.get_all_permissions()
        return context

viewer/templates/base.html
{% load static %}

<html {% if LANGUAGE_CODE %}lang="{{ LANGUAGE_CODE }}"{% endif %}>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>HollyMovies</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/viewer.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  <script>
    {% if messages %}
      {% for message in messages %}
        alert('{{message}}')
      {% endfor %}
    {% endif %}
  </script>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container fixed">
      <a class="navbar-brand" href="/">HollyMovies</a>
      <button
        class="navbar-toggler" type="button"
        data-toggle="collapse" data-target="#navbarNavAltMarkup"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link active" href="/">
            Home
          </a>
          <a class="nav-item nav-link active" href="{% url 'movie_create' %}">
            New Movie
          </a>
          <a class="nav-item nav-link active" href="/admin">
            Admin Panel
          </a>
        </div>
      </div>


      <div class="navbar-nav ml-auto">
        <div class="nav-item dropdown">
          {% if user.is_authenticated %}
            <a class="nav-link active dropdown-toggle" href="#" data-toggle="dropdown">
              {% if user.first_name %}Hello, {{ user.first_name }}!
              {% else %}Hello, {{ user.username }}!{% endif %}
            </a>
            <div class="dropdown-menu dropdown-menu-right">
              <a class="dropdown-item text-right" href="{% url 'accounts:logout' %}">Logout</a>
              <a class="dropdown-item text-right" href="{% url 'accounts:password_change' %}">Change password</a>
            </div>
          {% else %}
            <a class="nav-link active dropdown-toggle" href="#" data-toggle="dropdown">
              You are not logged in.
            </a>
            <div class="dropdown-menu dropdown-menu-right">
              <a class="dropdown-item text-right" href="{% url 'accounts:login' %}">Login</a>
              <a class="dropdown-item text-right" href="{% url 'accounts:sign_up' %}">Sign Up</a>
            </div>
          {% endif %}
        </div>
      </div>


    </div>
  </nav>
  <div class="container">
    <div class="jumbotron">
      {% block content %}{% endblock %}
    </div>
  </div>
</body>

</html> 

viewer/templates/form.html
{% extends "base.html" %}

{% block content %}
<form method="post">
  {% csrf_token %}
  <table>{{ form }}</table>
  <input type="submit" value="Submit" class="btn btn-primary">
</form>

{% endblock %}

viewer/templates/viewer/hello.html
{% extends "base.html" %}

{% block content %}
  <h1>Welcome to HollyMovies!</h1>
  {% for adjective in adjectives %}
    {% if adjective != 'cruel' %}
      <p>This is a {{ adjective }} world...</p>
    {% endif %}
  {% endfor %}
{% endblock %}

viewer/templates/viewer/hello_simple.html
{% extends "base.html" %}

{% block content %}
    <h1>Hello World</h1>
    <h2>Hello Beautiful World</h2>
    <h3>Hello Wonderful World</h3>
    <h4>Hello {{ s }} World</h4>
{% endblock %}

viewer/templates/viewer/movie_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<form method="post">
  {% csrf_token %}
  <p>
    Are you sure you want to delete the movie "{{ movie.title}}" from database?
  </p>
  <input type="submit" value="Delete" class="btn btn-danger">
</form>

{% endblock %}

viewer/templates/viewer/movie_details.html
{% extends "base.html" %}
{% block content %}
<h1>{{ movie.title }}</h1>
<h2>{{ movie.released }}</h2>
<h3>{{ movie.genre}}</h3>
<p>
  <strong>Rating:</strong> {{ movie.rating }}
</p>
<p>
  {{ movie.description|linebreaksbr }}
</p>




{% endblock %}

viewer/templates/viewer/movies.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1>Welcome to Holly Movies</h1>
<ul>
  {% for movie in object_list %}
    <li>
      {{ movie.title }} ({{ movie.released.year }}) - {{ movie.genre.name }}
      <a href="{% url 'movie_details' movie.pk %}">View</a> -
      <a href="{% url 'movie_update' movie.pk %}">Update</a> -
      <a href="{% url 'movie_delete' movie.pk %}">Delete</a>
    </li>
  {% endfor %}
</ul>
<img src="{% static 'img/cinema.jpg' %}" alt="picture of cinema">
<img src="{% static 'img/action.jpg' %}" alt="picture of cinema">

{% endblock %}